c**************************************
      BLOCK DATA BDMol
c**************************************
c
c      March 20, 1990
c...date last changed 19 February, 2002
c
      INCLUDE  'Species_2002.cmn'
      INCLUDE  'Molec.cmn'
c
      DATA (MOLID(I),I=0,NMOL)/ '   All',
     1'   H2O','   CO2','    O3','   N2O','    CO','   CH4','    O2',
     2'    NO','   SO2','   NO2','   NH3','  HNO3','    OH','    HF',
     3'   HCl','   HBr','    HI','   ClO','   OCS','  H2CO','  HOCl',
     4'    N2','   HCN',' CH3Cl','  H2O2','  C2H2','  C2H6','   PH3',
     5'  COF2','   SF6','   H2S',' HCOOH','   HO2','     O','ClONO2',
     6'   NO+','  HOBr','  C2H4'/
c
      END

